Airdrop Fixes
UniverseXYZ/XYZ-DAO-Frontend pull request #112
Opened 2022-04-15 11:58 UTC by ivanshterev18

- showing airdrop amount on the yield farming page
- updated the claim button to redirect the user to the airdrop page
- updated airdrop page text

## Related Issues

- [https://app.shortcut.com/universexyz/story/3546/update-claim-button-on-the-yield-farming-page](https://app.shortcut.com/universexyz/story/3546/update-claim-button-on-the-yield-farming-page)
- [https://app.shortcut.com/universexyz/story/3539/update-texts](https://app.shortcut.com/universexyz/story/3539/update-texts)

2022-04-15 12:02 UTC, vikinatora requested changes

2022-04-15 12:02 UTC, vikinatora commented on src/modules/airdrop/index.tsx
> +            forfeit forfeit a portion of your balance. Your total claimable amount will rise whenever someone forfeits a
`forfeit forfeit` should be only `forfeit`

2022-04-15 12:02 UTC, vikinatora commented on src/modules/airdrop/index.tsx
> +            portion their reward.
it should be `a portion **of**`

2022-04-15 12:02 UTC, taskudis requested changes

2022-04-15 12:02 UTC, taskudis commented on src/modules/airdrop/index.tsx
> +            forfeit forfeit a portion of your balance. Your total claimable amount will rise whenever someone forfeits a
I think there is a typo here.

2022-04-15 12:08 UTC, taskudis approved these changes

2022-04-18 06:27 UTC, taskudis approved these changes

2022-04-18 06:28 UTC, merged